### ISSUE TITLE
Google Analytics code included after the <body> tag, not before the </body> one

### ISSUE THREAD

**Issue by cimm** [kangguru/rack-google-analytics#1]
Hi,

I added the 2 lines you mention in the Readme to my config.ru file and restarted my application (running Rails 3.0.0.beta4) and it seems to work nicely. The problem is the Google Analytics JavaScript is included at the top of the file, right after the opening body tag, not before the closing one as you mention. This is not a big deal but for performance reasons it would be better at the bottom.

I have to admit that this is the very first time I use a Rack app so maybe I'm just doing it plainly wrong.

Thanks!

**Comment by leehambley** [comment]
cimm, nice catch - I actually need to make a few changes to this (things blow up if sending a response that doesn't have a body tag at all for example…) I'll patch and ping you when I have pushed some fixes.

Thanks for the interest!

**Comment by cimm** [comment]
Hope to patch it myself in the future... just not a Rack person yet. Thanks for the quick reply!

**Comment by cimm** [comment]
I stopped complaining and wrote a patch, for future reference: http://github.com/cimm/rack-google-analytics/commit/3fafa09a70cbecba1919d9e06fb86986ca70352e
