### ISSUE TITLE
Method _trackPageLoadTime is deprecated

### ISSUE THREAD

**Issue by rhb** [kangguru/rack-google-analytics#10]
I noticed this error via the Chrome analytics debugger extension:

```
Method _trackPageLoadTime is deprecated. _trackPageLoadTime is deprecated. Site Speed tracking is enabled by default with trackPageview call at 1% sampling. Use _setSiteSpeedSampleRate for changing sample rate. 
```

Here is a good summary of the new function:
http://stackoverflow.com/questions/6166074/how-does-gaq-push-trackpageloadtime-work

Related: Issue #4

**Comment by anicholson** [comment]
So all we need to do is remove that from the templates, right?
