### ISSUE TITLE
Request for tagging releases

### ISSUE THREAD

**Issue by rajudev** [kangguru/rack-google-analytics#13]
Tagging will help packaging this library for Debian. Currently the gem file does not contain any test and we like to run tests during packaging.

**Comment by smontgomerie** [comment]
What does this mean? There's a fairly extensive suite of test-unit tests. How do you add those to the Gemfile for packaging?

**Comment by kangguru** [comment]
form now on there should be also tags when an new version is released

https://github.com/leehambley/rack-google-analytics/tags
