### ISSUE TITLE
please leave CHANGELOG.md and tests in the gem

### ISSUE THREAD

**Issue by boutil** [kangguru/rack-google-analytics#24]
Hi,

Your Ruby library has been packaged for Debian. The package is created from the gem with a tool called gem2deb. In order to ensure that packages are working, tests are enabled during the construction of the package. That is why it would be great if you could keep the tests in the gem. I think it could be useful for direct users of the gem to be able to run the tests.

Could you keep also the changelog, as it would allow users to keep track of the changes between successive release?

Thanks in advance

Cédric

**Comment by kangguru** [comment]
i don't think that there were any plans to remove the tests from the gem :) Also i don't see a near future need to remove the changelog. So i think you can feel safe about that.
