### ISSUE TITLE
please move version.rb into lib/rack/google-analytics

### ISSUE THREAD

**Issue by boutil** [kangguru/rack-google-analytics#25]
Hi,

most of other rack extensions I know install the version file in lib/rack/name_extension/version.rb. Would you mind considering moving lib/rack/version.rb to lib/rack/google-analytics? That would ease the work of people packaging this gem, since it would avoid possible conflicts with other extensions.

Thank you

**Comment by kangguru** [comment]
actually they version.rb existed in two locations i've removed the obsolete on in lib/rack/

see d34af6ef7c5d285915fa34a489d186c0fa5de705
