### ISSUE TITLE
New feature: make the tracking code environment dependent

### ISSUE THREAD

**Issue by cimm** [kangguru/rack-google-analytics#3]
I missed one little feature in this app: environment dependency. I like to show the tracking code only in my production environment as I don't want to count the hits I'm generating while developing or testing. 

I added an extra parameter where you can specify the environment if you are interested: http://github.com/cimm/rack-google-analytics/commit/e505150d3bbd6dd4a72d8e7147d5b415fed94954 It uses an `:env => "development"` parameter and will default to the production environment when nothing is given.

I'll do a new pull request so you can include it in the master... if you like it.

**Comment by cimm** [comment]
These changes have been merged in the master, thanks Lee.

**Comment by rhb** [comment]
I didn't see this in master, did it get merged in?  Also - is there any way to disable the google-analytics insertion for specific namespaces?  For example - if I don't want to track traffic to my /admin pages?
