### ISSUE TITLE
Demographics and Interests report support

### ISSUE THREAD

**Issue by nilsmedina** [kangguru/rack-google-analytics#39]
When I try to access Demographics and Interests overview, I get this : 

> Your Demographics and Interest Reports have been enabled, but your Analytics tracking code does not include the necessary support to show them. Learn more about the simple, one-line, one-time change to your tracking code to add this support.

Along with this message there is a button to "validate tracking code", which fails.
Are Demographics and Interests supported with this gem? If yes, any idea on how I can fix it?

**Comment by kangguru** [comment]
Are you using 1.0.0? or one of the older versions?

**Comment by nilsmedina** [comment]
yes, I am using 1.0.0

**Comment by kangguru** [comment]
1.0.0 is using the new universal analytics, which unfortunately has no support for "Demographics and Interests"

> Universal Analytics does not currently support the the dc.js JavaScript and related features (Remarketing, Google Display Network Impression Reporting, DoubleClick Campaign Manager Integration, and the Google Analytics Demographics and Interests Reports). If you use any of these features, upgrade to Universal Analytics after dc.js is supported. 
> https://developers.google.com/analytics/devguides/collection/upgrade/

though you can still use 0.14.0 with this option set:

```
config.middleware.use Rack::GoogleAnalytics, tracker: 'UA-xxxxxx-x', advertising: true
```

**Comment by nilsmedina** [comment]
oops, I must admit I didn't research issues on google side, sorry for that :)
Anyway, thanks!

**Comment by kangguru** [comment]
no worries :) let me know if it all works with the old version

**Comment by nilsmedina** [comment]
I will stay on the universal analytics for this page because it's not such a big deal, but it's good to know for future reference :)
