### ISSUE TITLE
TurboLinks

### ISSUE THREAD

**Issue by fascox** [kangguru/rack-google-analytics#50]
have issue with this gem and turbo links. Realtime page view are not tracked following links on website. It will track only on page refresh. It si compatible with turbo links enabled?

Rails 4.1

**Comment by kangguru** [comment]
no, this is not supported. please migrate to [Rack::Tracker](https://github.com/railslove/rack-tracker) where i just made the needed changes to make it work with turbolinks. (please checkout master, its not released yet)

``` ruby
config.middleware.use Rack::Tracker do
    handler Rack::Tracker::GoogleAnalytics, tracker: 'UA-YYYZZZZ-1', position: :body
end
```

you need to specify the `position` - option, so the GA snippit isn't rendered in the head, what would be the default.

**Comment by kelso** [comment]
@kangguru Many thanks for pointing us to Rack::Tracker, it works with turbolinks!
Just for the info, let me update your snippet according to the current Rack::Tracker docs:

```
config.middleware.use(Rack::Tracker) do
  handler :google_analytics, { tracker: 'UA-YYYZZZZ-1', position: :body }
end
```

**Comment by kangguru** [comment]
@kelso cool, glad to here that!

both snippits should (hopefully) do the same, although, the one you posted is more elegant.

but, there is actually an issue with turbolinks railslove/rack-tracker#26 if you could check that out, i'd be very grateful, as i don't have a turbolinks app at hand right now.
