### ISSUE TITLE
Only enable in production?

### ISSUE THREAD

**Issue by jjwilliams** [kangguru/rack-google-analytics#51]
I tried moving the init code to production.rb, but it still loads in dev mode. Any way to specify the env to run in?

**Comment by jjwilliams** [comment]
Nevermind, it helps when I move it to the right damn file. I think its time for sleep.

**Comment by kangguru** [comment]
:D 

no worries. btw. did you have a look at [Rack::Tracker](https://github.com/railslove/rack-tracker)? Thats the successor of this Gem
