### ISSUE TITLE
Injecting custom variables before _trackPageView?

### ISSUE THREAD

**Issue by danielgrippi** [kangguru/rack-google-analytics#7]
Is there some sort of way to inject custom tracking variables on page load?  I'm trying to segment user roles across page views, which means I need to push to any custom tracking to `_gaq` BEFORE `_trackPageView` is pushed to the variable:

http://stackoverflow.com/questions/5191408/google-analytics-setcustomvar-strange-data-in-my-dashboard

I've looked through the gem and haven't quite seen a way to do this.  Am i missing something here?

**Comment by leehambley** [comment]
I'd recommend making a TrackingVariablesMiddleware - these only need to be something super simple (like a lambda/proc) and install that in your rails stack. 

I can really recommend [the Railscast about Rack](http://railscasts.com/episodes/151-rack-middleware) - and it's a correct separation of concerns. 

If you have a business need to put tracking vars in the page, write a middleware that does it.

If those variables get picked up by GA, include a middleware that loads GA.

Hope this helps, but I probably won't make any ~~significant~~ changes to this gem, as it works pretty much perfectly!

**Comment by smontgomerie** [comment]
@danielgrippi I've forked this project and added this functionality: 
http://github.com/smontgomerie/rack-google-analytics

**Comment by leehambley** [comment]
@smontgomerie unless you are going to send a pull request, please rename your project, this project namespace is already polluted with 3-5 implementations with almost identical names, and almost identical features.

For your own sake, I'd recommend picking something to differentiate your project, or I can happily give you commit access here to do your maintenance (also at Rubygems.org) 

This project "works for me" (and more often than not, I have special conditions that means that I cannot use this middelware)
