### ISSUE TITLE
rake aborted! 

### ISSUE THREAD

**Issue by danielsz** [kangguru/rack-google-analytics#8]
I must have missed something obvious.
I'm trying to use the gem in a rails app. 

The Gemfile has 
gem 'rack-google_analytics', :require => "rack/google_analytics"

I added to environments/production.rb:

  config.gem 'rack-google-analytics', :lib => 'rack/google-analytics'
  config.middleware.use Rack::GoogleAnalytics, :tracker => 'UA-31388307-1', :domain => "tuppu.net", :multiple => true

Upon the rake assets:precompile stage (locally and on heroku) I get the following.

rake aborted!
rack-google-analytics is not part of the bundle. Add it to Gemfile.

What's wrong?

Thanks, Daniel

**Comment by leehambley** [comment]
Looks like you mixed up "rack-google_analytics" and "rack-google-analytics" - if it's anything more more than that, please post back, otherwise close the ticket :smile:

**Comment by danielsz** [comment]
Note to self: don't post an issue at 3 AM, just sleep on it. 

And thanks, Lee.
